name: Test UWLCM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runs-on: ubuntu-20.04
  print_ref:
    steps:
    - run: echo ${{events.github.ref}}
#  call_test_uwlcm_hlpr:
#    uses: igfuw/UWLCM/.github/workflows/test_uwlcm_hlpr.yml@${{events.github.ref}}
#      with:
#        UWLCM_sha: ${{ events.github.sha }} # merge PR SHA
#        libcloudphxx_sha: git rev-parse https://github.com/igfuw/libcloudphxx
#        libmpdataxx_sha: git rev-parse https://github.com/igfuw/libmpdataxx
